### ISSUE TITLE
Problem with URL in mount_form method

### ISSUE THREAD

**Issue by danielbehrendt** [tanthammar/tall-forms#10] opened 2020-08-16 21:24 UTC
There seems to be a problem with the `mount_form` method.

`$this->previous = \URL::previous();` is causing an `CorruptComponentPayloadException`:

> Livewire encountered corrupt data when trying to hydrate the [xyz] component. Ensure that the [name, id, data] of the Livewire component wasn't tampered with between requests.

If I comment out line 38 in FormComponent.php everything works fine. I use the latest versions of laravel, livewire and tall-forms.

**Comment by danielbehrendt** [comment] 2020-08-17 15:36
I don't know if this is the right way but encoding and decoding the previous URL seems to fix the problem:

https://github.com/danielbehrendt/tall-forms/commit/bf11d2d116e5e4d5fb6dd7d1be127989377ef970

**Comment by tanthammar** [comment] 2020-08-17 20:11
I am unable to reproduce your error in my environment. 
- Tried both with embedded form and Route::livewire
- Tried both create and update form.

I'm on Laravel 7.25.0
Livewire 1.3.2
Tall-forms dev-master

- Can you please post your entire component. 
- Are you embedding your form or do you use Route::livewire
- Is it a create or update form?

I don't mind approving your PR but I'd like to find out if/why this is happening for you and not me :)

**Comment by danielbehrendt** [comment] 2020-08-17 20:41
Yes, seems so. but I haven't found out what it is. The only thing I found out (as I mentioned before) is that encoding and decoding the previous URL fixes the problem.

When I enter any other URL (manually) it also seems to work (even without encoding). It's really hard to find out what's going on here.

**Comment by tanthammar** [comment] 2020-08-17 20:42
Can you please post your entire component.

**Comment by tanthammar** [comment] 2020-08-17 20:43
Have you dd() the url? What does it look like, any strange chars?

**Comment by danielbehrendt** [comment] 2020-08-17 20:43
```
<?php

namespace App\Http\Livewire\Auth\User;

use App\User;
use Illuminate\Support\Facades\Hash;
use InvalidArgumentException;
use Spatie\Permission\Models\Role;
use Tanthammar\TallForms\Field;
use Tanthammar\TallForms\FormComponent;

class CreateForm extends FormComponent
{
    public $roles;

    public function mount()
    {
        $this->fill([
            'formTitle' => null,
            'action' => 'create',
            'spaMode' => false,
            'showGoBack' => true,
            'inline' => true,
            'form_wrapper' => null,
        ]);

        $this->mount_form(); // do not remove! sets the form properties
    }

    /**
     *
     * @return array
     */
    public function fields()
    {
        return [
            Field::make('Name')->input()->rules('required'),
            Field::make('E-Mail', 'email')->input('email')->rules(['required', 'email', 'unique:users,email']),
            Field::make('Password')->input('password')->rules(['required', 'confirmed']),
            Field::make('Password confirmation')->input('password')->rules(['required']),
            filled($this->roles) ? Field::make('Roles', 'role_ids')
                ->checkboxes($this->roles)
                ->relation()
                ->rules('nullable|array|exists:roles,id') : null,
        ];
    }

    /**
     *
     * @return void
     * @throws InvalidArgumentException
     */
    public function beforeFormProperties()
    {
        // set the checkboxes options
        $this->roles = Role::query()->select('id', 'name')->get()->pluck('id', 'name')->all();
    }

    /**
     *
     * @return array
     */
    public function rulesIgnoreRealtime()
    {
        return ['confirmed'];
    }

    /**
     *
     * @return void
     */
    public function create($formData)
    {
        User::create([
            'name' => $formData['name'],
            'email' => $formData['email'],
            'password' => Hash::make($formData['password']),
        ]);
    }

    /**
     *
     * @param array $relationshipData
     * @return void
     */
    public function relations($relationshipData)
    {
        // get the array data via the field name
        $selectedRoles = data_get($relationshipData, 'role_ids');

        // if the user unselected all available roles it means we have to detach any existing relations
        if (blank($selectedRoles)) {
            $this->model->roles()->detach(); //detach all existing relations
        } else {
            // in this example we scoped the roles to the users current team, so we check which roles the user is allowed to attach
            $allowedToSync = filled($selectedRoles) ? array_intersect($selectedRoles, array_values($this->roles)) : [];
            if (filled($allowedToSync)) {
                $this->model->syncRoles($selectedRoles);
            }
        }
    }
}

```

**Comment by tanthammar** [comment] 2020-08-17 20:50
How does the user arrive to this form. What is the previous url?
(Your component looks correct)

**Comment by tanthammar** [comment] 2020-08-17 20:52
Or you can add {{ $previous }} to your view, where you embed the form, to see the url printed.
Does it match what you expect?

**Comment by tanthammar** [comment] 2020-08-17 20:58
It must be some strange chars in your prevoius url. 
urlencode() removes all non-alphanumeric characters except `* -_. `

**Comment by danielbehrendt** [comment] 2020-08-17 20:59
Ok, it looks like this only happens if the previous URL contains a port number. Currently the previous URL looks like:

`https://foo.myproject.test:3000/users` as I'm using `browserSync`.

**Comment by tanthammar** [comment] 2020-08-17 21:23
It is probably the `:`
Can you try, to manually change $previous to, `https://foo.myproject.test3000/users` 
Just to see if it is the `:`

**Comment by danielbehrendt** [comment] 2020-08-17 21:29
Still the same problem, as long as I'm using the `browserSync` served URL in browser: `https://foo.myproject.test:3000/users/edit/1`. On `https://foo.myproject.test/users/edit/1` everything works fine.

**Comment by tanthammar** [comment] 2020-08-17 22:05
Ok :)
 I  just released a new version and I added the change you need. (docs not ready for new field types, will fix that tomorrow)

Think this might happen to others so I thought better to implement it now.

Thank you for you help.
 
(It will take a few minutes, or sometimes hours before the release is available via composer update)

Can I close this issue?

**Closed as completed** 2020-08-17 22:40 UTC
Labels: bug, fixed
